### ISSUE TITLE
v0.1.21 breaks the Middleman gem

### ISSUE THREAD

**Issue by danhalliday** [datocms/ruby-datocms-client#1]
Middleman Gem calls `Dato::Local::Site::load` (https://github.com/datocms/middleman-dato/blob/master/lib/middleman_dato/middleman_extension.rb#L27), which is no longer present here https://github.com/datocms/ruby-datocms-client/blob/master/lib/dato/local/site.rb.

**Comment by stefanoverna** [comment]
Hi Dan,
thanks for the report! Just released middleman-dato v0.5.22 to solve the problem.

--
Stefano Verna
CTO @ Cantiere Creativo

**Comment by danhalliday** [comment]
Amazing thanks, yes that solves it.
